version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 10
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 10
    groups:
      docker:
        patterns:
          - "*"
