# Sample tasks/main.yml for ansible-playbook
# Copyright (c) 2025 shinGETsu Project.

- name: install packages
  apt:
      pkg:
        - make
        - patch
        - python3-pil
        - supervisor
        # installed for ansible
        #- python3
        #- python3-jinja2

- name: make /etc/saku directories
  file:
    path: /etc/saku
    state: directory
    recurse: true

# put your config files to files/conf/
# sample files are doc/sample/
- name: put config files
  copy:
    src: '{{ item }}'
    dest: /etc/saku/{{ item | replace(role_path + '/files/conf', '') }}
  with_fileglob:
    - 'conf/*'
  notify: restart saku

- name: create shingetsu user
  user:
    name: shingetsu
    group: users
    shell: /bin/false
    home: /var/local/run/saku

- name: make directories
  file:
    path: '{{ item }}'
    state: directory
    recurse: true
    owner: shingetsu
    group: users
  with_items:
    - /var/lib/saku/cache
    - /var/local/log/saku
    - /var/local/run/saku

- name: make source directory
  file:
    path: /usr/local/src/saku
    state: directory
    recurse: true

- name: checkout saku
  git:
    repo: https://github.com/shingetsu/saku.git
    dest: /usr/local/src/saku

# put your supervisor.conf to files/
# sample is doc/sample/supervisor.conf
- name: put supervisor config
  copy:
    dest: /etc/supervisor/conf.d/saku.conf
    src: supervisor.conf

- name: stop saku
  shell:
    cmd: supervisorctl stop saku

- name: remove installed saku
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /usr/local/bin/saku
    - /usr/local/lib/saku
    - /usr/local/share/saku
    - /usr/local/share/doc/saku

- name: install saku
  shell:
    cmd: make && make install
  args:
    chdir: /usr/local/src/saku
  when: not ansible_check_mode

- name: start saku
  shell:
    cmd: supervisorctl start saku

- name: put shingetsu cron
  copy:
    dest: /etc/cron.d/shingetsu
    content: |
      # m  h dom mon dow user      command
       38  *   *   *   * shingetsu /usr/local/lib/saku/mkrss
